service: my-serverless-app

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1 # Optional: AWS-Region
  environment: # Optional: Umgebungsvariablen
    NODE_OPTIONS: --enable-source-maps --stack-trace-limit=1000

functions:
  #Einkauf trigger + Lieferanten anzeigen lassen
  getLieferanten:
    handler: src/Handler/handlerGetLieferanten.getLieferanten
    events:
      - http:
          path: getLieferanten
          method: get

  sendLieferanten:
    handler: src/responseSender/sendLieferanten.sendLieferanten
    events:
      - http:
          path: sendLieferanten
          method: post
          cors: true

  #Ausgewählten Lieferanten an DB übergeben und Mats für diesen zurückschicken
  getLieferantFE:
    handler: src/Trigger/getLieferantFE.getLieferantFE
    events:
      - http:
          path: getLieferantenFE
          method: post

  getMatLief:
    handler: src/Handler/handlerGetMatLief.getMatLief
    events:
      - http:
          path: getMatLief
          method: post

  sendMatLief:
    handler: src/responseSender/sendMatLief.sendMatLief
    events:
      - http:
          path: sendMatLief
          method: post

  #Material des Lieferanten und Lieferant übergeben und
  #Mat, Lief und Link aus DB holen und zurücksenden

plugins:
  - serverless-offline
  - serverless-plugin-typescript

custom:
  serverless-offline:
    log: true
    httpPort: 3001 # Der lokale Server läuft auf Port 3001
    noPrependStageInUrl: true # Kein Prefix für Umgebungen (z. B. dev)

package:
  individually: true # Optional: Nur genutzte Dateien und Dependencies in das Deployment-Paket aufnehmen
