service: my-serverless-app

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1 # Optional: AWS-Region
  environment: # Optional: Umgebungsvariablen
    NODE_OPTIONS: --enable-source-maps --stack-trace-limit=1000

functions:
  getLieferanten:
    handler: src/DBHandler/handlerGetLieferanten.getLieferanten
    events:
      - http:
          path: getLieferantenDB
          method: get

  sendLieferanten:
    handler: src/FrontendData/sendLieferanten.sendLieferanten
    event:
      - http:
          path: sendLieferantenFrontend
          method: post

  getLieferantFE:
    handler: src/FrontendData/getLieferantFE.getLieferantFE
    events:
      - http:
          path: getLieferantenFE
          method: get

  getMatLief:
    handler: src/DBHandler/getMatLief.getMatLief
    events:
      - http:
          path: getMatLief
          method: get

  sendMatLief:
    handler: src/DBHandler/sendMatLief.sendMatLief
    events:
      - http:
          path: sendMatLief
          method: post

plugins:
  - serverless-offline
  - serverless-plugin-typescript

custom:
  serverless-offline:
    httpPort: 3000 # Der lokale Server läuft auf Port 3000
    noPrependStageInUrl: true # Kein Prefix für Umgebungen (z. B. dev)

package:
  individually: true # Optional: Nur genutzte Dateien und Dependencies in das Deployment-Paket aufnehmen
