service: my-serverless-app

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1 # Optional: AWS-Region
  environment: # Optional: Umgebungsvariablen
    NODE_OPTIONS: --enable-source-maps --stack-trace-limit=1000

functions:
  getData:
    handler: src/handler.getData
    events:
      - http:
          path: getData
          method: get

plugins:
  - serverless-offline
  - serverless-plugin-typescript

custom:
  serverless-offline:
    httpPort: 3000 # Der lokale Server läuft auf Port 3000
    noPrependStageInUrl: true # Kein Prefix für Umgebungen (z. B. dev)

package:
  individually: true # Optional: Nur genutzte Dateien und Dependencies in das Deployment-Paket aufnehmen
