### POST request to send getBestellung
POST http://localhost:3001/validatedGetMatLief

{
    "Bestellung": {
            "LiefID": 1,
            "LagerID": 1,
            "Datum": "2011-11-11",
            "Materialien": [
                {
                    "MatID": 1,
                    "Menge": 20
                },
                {
                    "MatID": 2,
                    "Menge": 20
                }
            ]
        }
}